name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Version
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          VERSION=${VERSION#v} # Remove 'v' prefix
          IFS='.' read -r -a PARTS <<< "$VERSION"
          MAJOR="${PARTS[0]}"
          MINOR="${PARTS[1]}"
          PATCH="${PARTS[2]}"
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "::set-output name=version::$NEW_VERSION"

      - name: Build Docker image
        run: docker build -t kubendrapandian10d/react-project:${{ steps.version.outputs.version }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push kubendrapandian10d/react-project:${{ steps.version.outputs.version }}
